### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by wang-xiaowu** [Drew233/Artitalk#107]
请按照本模板编写issues
一直都是可用的, 但是这些天却出现跨域问题, 我挂了代理
**描述**
请详细的描述你所遇到的bug

**出现bug的页面**
页面链接：

**重现**
请重现你遇到bug的过程

**截图**
如果方便的话，在这里添加截图来更清晰的说明你遇到的bug。
![image](https://user-images.githubusercontent.com/44340137/185886294-f43a4952-d2be-4784-929a-d16ccc2c0a1c.png)

**桌面设备 (please complete the following information):**
 - 操作系统: [e.g. iOS]
 - 浏览器 [e.g. chrome, safari]
 - 版本 [e.g. 22]

**移动设备 (please complete the following information):**
 - 型号: [e.g. iPhone6]
 - 操作系统: [e.g. iOS8.1]
 - 浏览器 [e.g. stock browser, safari]
 - 版本 [e.g. 22]

**其他内容**
在此处添加其他信息

**Comment by 612901** [comment]
因为leancloud国际版域名不再为中国地区提供服务，得绑定自定义域名，将说说权限调为所有用户，在_user新建一个用户
