### ISSUE TITLE
点赞功能缺陷

### ISSUE THREAD

**Issue by Linhk1606** [Drew233/Artitalk#12]
请按照本模板编写issues

**描述**
我发现点赞完以后刷新页面可以重复点赞，这个有点不太好
建议记录点赞者的IP存在数组里，然后每次比对，如果相同就显示为已点赞？(估计码量不小啊)

**出现bug的页面**
页面链接：

**重现**
请重现你遇到bug的过程

**截图**
如果方便的话，在这里添加截图来更清晰的说明你遇到的bug。

**桌面设备 (please complete the following information):**
 - 操作系统: [e.g. iOS]
 - 浏览器 [e.g. chrome, safari]
 - 版本 [e.g. 22]

**移动设备 (please complete the following information):**
 - 型号: [e.g. iPhone6]
 - 操作系统: [e.g. iOS8.1]
 - 浏览器 [e.g. stock browser, safari]
 - 版本 [e.g. 22]

**其他内容**
在此处添加其他信息

**Comment by Drew233** [comment]
实现这个功能之前，在群里我们讨论过这个点赞是否需要限制。最后决定不进行限制。
对于你说的纪录ip，首先是难于实现（毕竟我们用的是leancloud），其次就是限制ip其实作用不大。
所以目前最稳妥的就是不限制

**Comment by Linhk1606** [comment]
哦

**Comment by inkss** [comment]
这个点赞没有防止暴力点击的功能（只要手速够快...

我在你网站一通瞎点

**Comment by Drew233** [comment]
暂时没有办法，以后可能会改进。不过暴力点击，确实不太好办

**Comment by inkss** [comment]
hansome 是这样处理的，每次点赞大概是将id存到一个cookie里，然后点另外一个说说，继续在这个cookie后面追加ID，然后用id做比较吧，如果已经有了就是重复点赞。
cookie的有效期是会话，一次浏览期间不允许重复点赞。

**Comment by Drew233** [comment]
之前考虑过这个，但是这个还是防止不了想暴力点赞的人。
所以防君子不防小人吧

**Comment by Linhk1606** [comment]
假设有人使用了某种工具点了一大堆的赞，会不会导致LeanCloud调用次数过多
之前Valine就是有报过这个漏洞，一大堆`undefined`用户刷了几百万个评论。。。

**Comment by Drew233** [comment]
如果有人刷，确实是可以的。。。
