### ISSUE TITLE
valine && artitalk 

### ISSUE THREAD

**Issue by inkss** [Drew233/Artitalk#13]
**描述你想实现或修改的功能**
valine 和 artitalk，能不能在初始化 artitalk 的时候检测 valine 或者 leancloud 的变量是否已经定义了，然后将其清除了，避免冲突呢？

**Comment by Drew233** [comment]
leancloud不允许同一个页面初始化两个不同的应用，不过原则上讲，只要你在存储说说的应用中新建valine所需的class应该是可以使用的。

**Comment by inkss** [comment]
能清除valine创建的应用吗？

**Comment by Drew233** [comment]
不用，其实可以这样理解，在说说页面使用的valine与整站使用的valine不在一个应用中

**Comment by inkss** [comment]
懂你意思了，以应用为准啊

**Comment by Drew233** [comment]
不过这只是理论可行，没试过

**Comment by inkss** [comment]
```log
Uncaught (in promise) TypeError: Cannot redefine property: applicationId
```

**Comment by Drew233** [comment]
不能用吗？😂

**Comment by inkss** [comment]
如果是走重置变量的思路呢，在定义的时候都会创建那些变量啊？

**Comment by Drew233** [comment]
初始化吗？就这两个会产生冲突(如果使用国内版的话还有serverurl)
```
var appID="";
var appKEY="";
```

**Comment by inkss** [comment]
serverurl 怎么重新设定啊

**Comment by Drew233** [comment]
```
var severurl=""
```

**Comment by inkss** [comment]
> 在说说页面使用的valine与整站使用的valine不在一个应用中

不同应用是可以使用你这个思路的

**Comment by Drew233** [comment]
嗯

**Comment by inkss** [comment]
如果是同一个应用，能公用变量吗？比如valine初始化出来的 AV 对象

**Comment by Drew233** [comment]
可以，但是对于valine的评论添加用户可能会与artitalk有冲突吧，这个我不是很清楚，因为artiitalk会对User进行权限上面的设置，valine我不知道

**Comment by inkss** [comment]
thx 啦，我是想到 pjax 兼容上，在跳转到说说页面时，先把 window.AV.applicationId 和 window.AV.applicationKey 置空，然后你这边正常初始化，离开页面后再次置空了

**Comment by Drew233** [comment]
pjax太顶了，其实可以给说说加个target="_blank"跳转新页面，就不会有问题了😄

**Comment by inkss** [comment]
那还要处理从这个页面离开的情况呀，而且刷新总觉得不好

**Comment by Drew233** [comment]
在之前解决mathjax的问题的时候我看到有人说可以重写pjax的刷新规则，但是我不会，如果你会的话可以尝试一下

**Comment by inkss** [comment]
你从这个页面，然后跳留言板  https://colsrch.top/Creator-said/

**Comment by inkss** [comment]
@Colsrch 你是用多应用吗? 说说和评论是分开的吗？

**Comment by inkss** [comment]
valine 似乎有点判断处理啊，没有重复初始化

**Comment by Drew233** [comment]
嗯？我不知道，没有仔细地试过

**Comment by Colsrch** [comment]
> 你从这个页面，然后跳留言板 [https://colsrch.top/Creator-said/，这个时候应该用的是说说的应用，原来的留言没有](https://colsrch.top/Creator-said/%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%97%B6%E5%80%99%E5%BA%94%E8%AF%A5%E7%94%A8%E7%9A%84%E6%98%AF%E8%AF%B4%E8%AF%B4%E7%9A%84%E5%BA%94%E7%94%A8%EF%BC%8C%E5%8E%9F%E6%9D%A5%E7%9A%84%E7%95%99%E8%A8%80%E6%B2%A1%E6%9C%89)

你发现了新的问题，我一直都没发现

**Comment by Colsrch** [comment]
> @Colsrch 你是用多应用吗? 说说和评论是分开的吗？

对，我是两个应用

**Comment by inkss** [comment]
不急不急，多好的范例

**Comment by MHuiG** [comment]
> valine 似乎有点判断处理啊，没有重复初始化

valine只在加载AV完成后进行初始化，加载完成AV后不再加载，因此不再初始化，所以就继承了你的AV。

**Comment by inkss** [comment]
@MHuiG 所以，仅以 valine 和 Artitalk 来说，那就收进出 Artitalk 页面之前、之后执行 `delete AV;` 就不会出来报错的问题了吧，这样子可以顺畅的 pjax 切换页面来着。
