### ISSUE TITLE
一直处于加载状态

### ISSUE THREAD

**Issue by Amumu547426** [Drew233/Artitalk#14]
![image](https://user-images.githubusercontent.com/55990007/86588105-a0757d80-bfbd-11ea-97dd-d43e5ed5f11b.png)

**Comment by Drew233** [comment]
这个是jquery没有正常加载，有你的链接吗？我可以去看看

**Comment by Amumu547426** [comment]
https://jpfly.xyz/talk/
谢谢

**Comment by Drew233** [comment]
你这是没加载jquery，主题自带的在后面了。
两种解决办法
1. 在markdown中的调用artitalk的上面写一个jquery
2. 找到你主题里面加载jquery的地方把artitalk加到下面

推荐用第一种

**Comment by Amumu547426** [comment]
十分感谢！误以为主题会先加载jquery。
