### ISSUE TITLE
Artitalk#Token安全

### ISSUE THREAD

**Issue by ChenYFan** [Drew233/Artitalk#16]
**即使Token设置为仅Write，还是有很大的安全隐患**

我无法理解为什么只要一层Base64就可以安全避开Token检测，文档对于加密Token轻描淡写。躲开了又如何，别人一旦盗取token，对于github账号就是毁灭性灾难。

Base64根本不算是加密，只是混淆，而且是双向的，这意味着别人可以轻松获得Token

Token意味着他人可以绕开双重验证和密码，即使是仅write也有可能造成滥用。Hexo官方在使用Travis-CI时就极其强调这一点。不过我在成功案例中发现没有一个人配置了token_pt。

此处比较建议可以试试非对称加密，用用户的用户名和密码生成密钥和公钥，公钥加密token_pt写在配置项里，用户登录时生成并解密。

或者直接加在Valine的变量里，不过不知道这样行不行。

也许上面说的可能严肃了点(*￣;(￣ *)，不过这个问题确实很严重。

再者，配置成功，感谢Artitalk！((*・∀・）ゞ→→，已经Star！希望做的更好！

安利一下自己的博客： [ChenYFのBlog&随口胡说](https://blog.cyfan.top/%E9%9A%8F%E5%8F%A3%E8%83%A1%E8%AF%B4/)

**Comment by Drew233** [comment]
怎么说呢，base64在这里并不是加密的作用，就算加密了，我们自己也会用到，加密是相当于没用的。
也是因为这个原因，一开始并没有想弄自定义仓库的配置项，存储大家资源的账号也是随意弄得。
不够如果真的对这个有要求到也可以解决，把token也放到leancloud上面就可以了。这段时间我在群里问一下把，如果都觉得有必要的话，就改成把token存储到leancloud中，这样安全性就大大提高了。

最后，感谢支持~

**Comment by Drew233** [comment]
base64编码一下主要是因为gh-pages会检测仓库中如果出现了token就会自动把token删除，套一下base64就可以绕过这个检测

**Comment by ChenYFan** [comment]
是的，Github为了防止Token泄露所以才设置了这个机制，正因为如此我们应该重视Token，而不是随意以接近明文形式存在，希望下次能开发好。

再支持一波，安利完成！

**Comment by Drew233** [comment]
嗯，其实刚加上这个我就想起来可以存在leancloud里面。
但是懒惰让我放弃修改哈哈哈

预计下个版本就会修复，感谢提出的建议~

**Comment by ChenYFan** [comment]
好的，加油！

**Comment by Drew233** [comment]
已修复哦~
