### ISSUE TITLE
 Artitalk背景色设置为变量或独立css

### ISSUE THREAD

**Issue by ChenYFan** [Drew233/Artitalk#17]
这个问题呢，Owner随意，不过越早越好，毕竟用着有点不爽。

**不方便直接修改主题配色**

诶呀配置全部写在一个js里头背景颜色和我主题不搭呀，我又不想自己修改js，我还想着获取最新版本呢 ~~【委屈】~~，希望下次能将主题配色写成变量形式放在配置里头好修改，感谢啦

**Comment by Drew233** [comment]
这个可以在md里面写css替换js里面的css
可以参考一下这个
https://cungudafa.blog.csdn.net/article/details/106224223

直接把css弄成配置项不太舒服

**Comment by ChenYFan** [comment]
好吧╮(╯-╰)╭我去试试
