### ISSUE TITLE
说说界面一直加载不出来，一直在“下雨”

### ISSUE THREAD

**Issue by YDTRINLEY** [Drew233/Artitalk#20]
请按照本模板编写issues

**描述**
一直加载不出来。
我是用HEXO-NEXT v7.8版本。
评论功能valine，已经在md文件里面，在开头用  comments: false 语句关闭了。

**出现bug的页面**
页面链接（我的说说网页）：：https://ydtrinley.github.io/shuo/

**重现**
请重现你遇到bug的过程
我是通过这个[网页](https://www.npmjs.com/package/artitalk )<npm i artital>命令安装artitalk，按照文档和哔哩哔哩的视频来配置的，
然后发现加载不出来……
PS: `<script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>`这句我在custom.styl中引用过了，所以没写在这个index.md文件中，不然会报错。

**截图**
这是我的配置md文件截图：
[source/shuo/index.md](https://github.com/YDTRINLEY/PicGo/blob/master/img/shuoshuo%E9%97%AE%E9%A2%981.png)

**桌面设备 (please complete the following information):**
 - 操作系统: [e.g. iOS]win10
 - 浏览器 [e.g. chrome, safari]chrome
 - 版本 [e.g. 22]

**其他内容**
这是我第一次使用github提交bug的系统，不知道问题有木有表达清楚。开发者辛苦了。先谢谢

**Comment by Drew233** [comment]
给我截图看看吧
就是你说说页面F12里面的console，我看看报错

**Comment by Drew233** [comment]
我自己刚才去看了一下，你的问题应该是jquery引入在artitalk后面了。
为什么`<script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>`放在index会报错？报的什么错

**Comment by YDTRINLEY** [comment]
https://raw.githubusercontent.com/YDTRINLEY/PicGo/master/img/shuoshuo%E9%97%AE%E9%A2%98%E5%8F%91F12.bmp
这是F12报错截图

**Comment by Drew233** [comment]
嗯，我刚才起床开电脑看了一下hhh
是jquery的问题，放在index.md会报什么错

**Comment by YDTRINLEY** [comment]
jQuery: Uncaught TypeError: Cannot read property 'nodeType' of undefined

> 嗯，我刚才起床开电脑看了一下hhh
> 是jquery的问题，放在index.md会报什么错

厉害~好早吖~
之前把jquery放在md文件里面开头部分，f12里面会显示报错“jQuery: Uncaught TypeError: Cannot read property 'nodeType' of undefined……”

**Comment by YDTRINLEY** [comment]
> 嗯，我刚才起床开电脑看了一下hhh
> 是jquery的问题，放在index.md会报什么错

我查了下这个bug，参考了别人的说法：[这个网页](https://www.wqh4u.cn/2019/09/10/Hexo-NexT%E9%AD%94%E6%94%B9%E7%B3%BB%E5%88%97-02-%E9%85%8D%E7%BD%AE%E5%8D%9A%E5%AE%A2%E8%83%8C%E6%99%AF%E8%BD%AE%E6%92%AD%E5%9B%BE/)，然后把jquery放到了custom.styl里面去了，这个bug提示就消失了

**Comment by Drew233** [comment]
那你就把jquery放在引用artitalk的上面，让他俩挨着试试

**Comment by Drew233** [comment]
因为artitalk需要jquery的支持。如果你是在引用artitalk的后面引用jquery的话会出现错误

**Comment by YDTRINLEY** [comment]
> 因为artitalk需要jquery的支持。如果你是在引用artitalk的后面引用jquery的话会出现错误

刚刚我试了下，把jquery放到head.swig里面，baidu.verification 语句后面：
`{%- if theme.baidu_site_verification %}
  <meta name="baidu-site-verification" content="{{ theme.baidu_site_verification }}">
{%- endif %}

<script src="https://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>

<link rel="stylesheet" href="{{ url_for(theme.css) }}/main.css">

{{ next_font() }}`
重新部署了下，然后到页面看源代码，jquery语句是显示在artitalk前面的~ 但说说还是加载不出来……
不知道是不是和音乐播放器有冲突啊？つ﹏⊂
我是不会代码的小白つ﹏⊂

**Comment by Drew233** [comment]
你现在部署了是吧，给我看看F12的报错吧

**Comment by YDTRINLEY** [comment]
> 因为artitalk需要jquery的支持。如果你是在引用artitalk的后面引用jquery的话会出现错误

而且发现把jquery语句改放在head.swig以后，之前那个报错又回来了：
·Uncaught TypeError: Cannot read property 'nodeType' of undefined
    at init.attr (jquery.min.js:5)
    at Function.access (jquery.min.js:4)
    at init.attr (jquery.min.js:5)
    at _delay (Aplayer-Controler.js:222)·

**Comment by Drew233** [comment]
你的播放器也需要jquery的支持吗

**Comment by Drew233** [comment]
哪有可能是jquery冲突了
等下午我回家给你康康吧

**Comment by YDTRINLEY** [comment]
![shuoshuo问题3-F12 - 副本](https://user-images.githubusercontent.com/61964021/88239459-0e58bf00-ccb7-11ea-9ec5-cd682367525d.png)
之前右边那只小人音乐播放控制器之前都一直没有显示出来，现在突然出现了，估计是jquery的引用才出来的吧 つ﹏⊂~ 不知道是不是对左边侧边栏的播放器有影响，我下午试试把右边那个卸载了，看看能不能把说说页面加载出来つ﹏⊂
谢谢你(●ˇ∀ˇ●)

**Comment by Drew233** [comment]
不好意思，一下子忙到了晚上

你的问题解决了吗？如果没有的话我们QQ联系一下吧，这样方便，把你博客文件发我一份我给你看看怎么改可以两个都不影响那样子

Artitalk交流群(QQ)：1104585229

**Comment by YDTRINLEY** [comment]
> 不好意思，一下子忙到了晚上
> 
> 你的问题解决了吗？如果没有的话我们QQ联系一下吧，这样方便，把你博客文件发我一份我给你看看怎么改可以两个都不影响那样子
> 
> Artitalk交流群(QQ)：1104585229

哇~好的谢谢你吖
我已经把那个右边的音乐播放控件（aplayer-controller）小人给删除了，然后把那个jquery语句放回md文件里面。这次是新的报错了，还是加载不出来……

**Comment by YDTRINLEY** [comment]
解决了，谢谢d=====(￣▽￣*)b
解决方法：

1. 我卸载了aplayer-controller插件 ； 然后再把jquery的语句粘贴回md文件中，这次没有再出现关于jquery的bug
2. 然后出现的另一个bug是：user权限没有设置对。重新去leancloud里面class  user列表权限最后的find权限设置全部人就可以加载了。
👍

**Comment by Drew233** [comment]
厉害厉害(ง •̀_•́)ง
