### ISSUE TITLE
希望能够兼容pjax！

### ISSUE THREAD

**Issue by BooLo** [Drew233/Artitalk#21]
请按照此模板编写issue

**描述你想实现或修改的功能**
基于Artitalk的说说页面在使用pjax时，无法正常加载出说说内容。需要手动刷新页面，或将该说说目录添加pjax屏蔽才能解决，造成体验性十分不好。希望Artitalk能够兼容pjax，使得内容正常加载！

**其他内容**
***

**Comment by Drew233** [comment]
这不是我该做的事啊，既然你能使用pjax屏蔽那不就可以了吗？

**Comment by BooLo** [comment]
> 这不是我该做的事啊，既然你能使用pjax屏蔽那不就可以了吗？

我只是提个建议啦，毕竟像valine是不需要屏蔽的。最主要是，如果都屏蔽了，那还用pjax干嘛是吧。如果非要屏蔽才能用，那......

**Comment by Drew233** [comment]
你什么主题？

**Comment by BooLo** [comment]
> 你什么主题？

Volantis

**Comment by Drew233** [comment]
首先valine是每个页面都有的，不需要重新加载也能显示倒也正常
其次可能就是作者添加pjax的时候已经把valine适配好pjax了

既然可以通过屏蔽解决，就这样吧

**Comment by Linhk1606** [comment]
Volantis 可以把你的artitalk页面 ban 掉 不启用 pjax

**Comment by Drew233** [comment]
很感谢你提的建议
这个问题最近确实很多人反馈，相比于volantis可以直接选择页面屏蔽pjax，其他主题没有这个配置项的就更难了

不过现在已知的解决方案都是重写pjax的刷新规则，所以这里可能不是我能左右的

**Comment by BooLo** [comment]
好哒，谢谢！
