### ISSUE TITLE
meelow主题添加 Artitalk  说说系统

### ISSUE THREAD

**Issue by abbw** [Drew233/Artitalk#25]
站点名称：**骑猪看月亮**
说说页面：**https://qzkyl.ml/shuoshuo/**
博客框架：**Hexo**
博客主题：**[hexo-theme-mellow](https://github.com/codefine/hexo-theme-mellow)**

本站支持游客发言，欢迎各位踊跃刷屏~

**Comment by abbw** [comment]
希望能加入成功案例让更多人看到

**Comment by Drew233** [comment]
已添加~
