### ISSUE TITLE
火狐浏览器打不开任何带有aritalk的页面

### ISSUE THREAD

**Issue by 49092095** [Drew233/Artitalk#3]
配置完成以后我可以用safari，Chrome打开带有aritalk的网页
然后我发现任何带有aritalk的网页我用火狐都打不开。比如[cungudafa的](https://cungudafa.top/artitalk/)。

**Comment by Drew233** [comment]
你好，我专门去下载了火狐，可以打开[cungudafa的。](https://cungudafa.top/artitalk/)
是否可以发一下你的链接？
