### ISSUE TITLE
建议从 _User 表中取作者数据

### ISSUE THREAD

**Issue by xaoxuu** [Drew233/Artitalk#4]
暂时还没用上，看文档好像每次发布都是指定头像的，可否考虑从 leancloud 的 `_User` 表中根据 `objectId` 获取发布者的各项信息呢？

**Comment by Drew233** [comment]
你好，填写头像图片的输入框只针对某次想自定义的情况。不是必填 默认使用script标签中的img变量作为头像

**Comment by xaoxuu** [comment]
那是不是 `_User` 表中的同一个用户呢？

**Comment by Drew233** [comment]
有指定的头像话 是会存储在class中的

**Comment by xaoxuu** [comment]
我之所以关注了这一点，是因为我用 leancloud 的 SDK 写过 iOS app，官方的用户系统挺完善的。感觉基于此做个山寨的微博这样的平台也是可行的。

**Comment by Drew233** [comment]
嗯嗯，我大概了解你的意思。不过说说的话，自己一个人发布就够了😂
之所以添加自定义头像 是为了方便有些小伙伴可能会做情侣博客之类的需求（其实这个无所谓的

**Comment by xaoxuu** [comment]
多人发布的话，各自登录自己的账号发，自己的浏览器一般会记住登录信息，这样应该还是比复制粘贴头像地址要方便。

**Comment by xaoxuu** [comment]
只要在 _User 表中给某个用户权限，这个用户就可以发。但是我不清楚前端怎么管理自己的个人信息，例如设置昵称、修改自己的头像。

**Comment by Drew233** [comment]
嗯嗯，多人发布的话这样确实会方便很多。下个版本我加一下这个功能吧。谢谢您提出的建议☺️

**Comment by Drew233** [comment]
> 只要在 _User 表中给某个用户权限，这个用户就可以发。但是我不清楚前端怎么管理自己的个人信息，例如设置昵称、修改自己的头像。

前段修改用户信息就不考虑了先，添加用户自己在leancloud添加就好了。毕竟说说是私人性的

**Comment by Drew233** [comment]
最新版现在已经是根据用户设置的头像进行存储~

**Comment by xaoxuu** [comment]
👍
