### ISSUE TITLE
关于弹出窗口

### ISSUE THREAD

**Issue by Linhk1606** [Drew233/Artitalk#7]
我建议弹出窗口应该放到外层，而非artitalk所在的那一层
因为我们的Volantis主题是卡片式设计，这样会导致弹出窗口在卡片里面，而不是在整块屏幕中央， https://blog.lhkstudio.me/time-machine/

---

另：我对这方面不是特别了解，所以用词可能不太准确，见谅

**Comment by Drew233** [comment]
我大概了解你的意思，之前确实没有考虑这方面。
下个版本会进行相关的修复。
感谢您提出的建议😊

**Comment by Drew233** [comment]
经过我多次尝试，暂时还无法解决
等以后慢慢fix吧

**Comment by Drew233** [comment]
fix
v2.2.0

**Comment by Linhk1606** [comment]
强啊老哥👍

**Comment by Drew233** [comment]
> 强啊老哥

主要还是什么都不会，一直在学习。希望越来越好🙏

**Comment by Linhk1606** [comment]
帮忙把我们主题那个也更新一下呗

**Comment by Drew233** [comment]
> 帮忙把我们主题那个也更新一下呗

已经PR了
